jobs:
  include:
    - stage: Test
      sudo: required
      services:
        - docker
      before_install:
        - openssl aes-256-cbc -K $encrypted_613f6608c56d_key -iv $encrypted_613f6608c56d_iv -in secrets.tar.enc -out secrets.tar -d
        - tar -xf secrets.tar -C config/
      install:
        - docker-compose build
        - docker-compose up -d app
        - until docker-compose exec mysql mysql -uroot --password=${MYSQL_ROOT_PASSWORD} -e 'SHOW DATABASES;'; do echo "mysql haven't ready yet"; done
      script:
        - docker-compose exec app rails db:migrate
        - docker-compose exec app bundle exec rspec
        - docker-compose exec app rails_best_practices .
