sudo: required
services:
- docker
language: generic
jobs:
  include:
  - before_install:
    - openssl aes-256-cbc -K $encrypted_7b9dbc922c26_key -iv $encrypted_7b9dbc922c26_iv
      -in secrets.tar.enc -out secrets.tar -d
    - tar -xvf secrets.tar -C config/
    install:
    - docker-compose build
    - docker-compose up -d app
    - until docker-compose exec mysql mysql -uroot --password=${MYSQL_ROOT_PASSWORD}
      -e 'SHOW DATABASES;'; do sleep 1; done
    script:
    - docker-compose exec app rails db:migrate > migrate.log
    - docker-compose exec app bundle exec rspec
    - docker-compose exec app rails_best_practices .
    after_failure:
    - cat migrate.log
