jobs:
  include:
    - stage: Test
      sudo: required
      services:
        - docker
      before_install:
        - openssl aes-256-cbc -K $encrypted_7b9dbc922c26_key -iv $encrypted_7b9dbc922c26_iv -in secrets.tar.enc -out secrets.tar -d
        - tar -xf secrets.tar -C config/
      install:
        - docker-compose build
        - docker-compose up -d app
        - sleep 10
      script:
        - docker-compose logs mysql
        - docker-compose exec app rails db:migrate
        - docker-compose exec app bundle exec rspec
        - docker-compose exec app rails_best_practices .
